spring:
  profiles:
    active: dev
  application:
    name: tea-api

server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true

logging:
  level:
    root: INFO
    com.ecotea.api: DEBUG
